#!/bin/sh
docker run -d --name squid3-ssl-debs docker.balsamiq.com/squid3-ssl-debs
docker cp squid3-ssl-debs:squid3-ssl-debs.tar.gz .
docker rm squid3-ssl-debs
mkdir -p debs
(cd debs ; tar xvfz ../squid3-ssl-debs.tar.gz)
docker build -t docker.balsamiq.com/squid3-ssl .
