#!/bin/bash

set -e

#HOST=$(hostname -A | tr -d ' ')
new_hostname=${HOST_NAME:-"squid-ssl.docker"}

sed -i "s|<HOST>|${new_hostname}|g" /etc/squid/openssl.cnf
sed -i "s|<HOST>|${new_hostname}|g" /etc/squid/squid.conf

mkdir -p /etc/squid/certs

if ! [ -f "/etc/squid/certs/${new_hostname}.crt" ]; then
  /usr/local/bin/mk-certs
fi

chown -R proxy:proxy /etc/squid/certs

cat "/etc/squid/certs/${new_hostname}.crt"

# /usr/sbin/squid -Nz

mkdir -p /var/cache/squid/squid_{1..4}
chown -R proxy:proxy /var/cache/squid
chown -R proxy:proxy /var/log/squid
chmod gou+w /var/log/squid
/usr/sbin/squid -Nz

exec /usr/sbin/squid -Nd2cs
